// Mocks generated by Mockito 5.4.6 from annotations
// in mind_metric/test/helper/mock_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i26;
import 'dart:io' as _i17;

import 'package:connectivity_plus/connectivity_plus.dart' as _i20;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i30;
import 'package:file_selector/file_selector.dart' as _i35;
import 'package:firebase_remote_config/firebase_remote_config.dart' as _i29;
import 'package:flutter/foundation.dart' as _i38;
import 'package:flutter/material.dart' as _i36;
import 'package:mind_metric/config.dart' as _i37;
import 'package:mind_metric/src/application/model/file_info.dart' as _i33;
import 'package:mind_metric/src/application/sync/job_connectivity.dart'
    as _i39;
import 'package:mind_metric/src/application/sync/job_manager.dart' as _i19;
import 'package:mind_metric/src/application/sync/job_timer.dart' as _i13;
import 'package:mind_metric/src/data/auth/auth_repository.dart' as _i15;
import 'package:mind_metric/src/data/auth/auth_service.dart' as _i2;
import 'package:mind_metric/src/data/auth/user_repository.dart' as _i4;
import 'package:mind_metric/src/data/auth/user_service.dart' as _i25;
import 'package:mind_metric/src/data/core/config_repository.dart' as _i5;
import 'package:mind_metric/src/data/core/log_services.dart' as _i11;
import 'package:mind_metric/src/data/core/remote_config/remote_config_repository.dart'
    as _i6;
import 'package:mind_metric/src/data/core/sync/job_repository.dart' as _i23;
import 'package:mind_metric/src/data/database/auth_settings_dao.dart' as _i9;
import 'package:mind_metric/src/data/database/auth_token_dao.dart' as _i7;
import 'package:mind_metric/src/data/database/core/app_database.dart' as _i14;
import 'package:mind_metric/src/data/database/job_dao.dart' as _i22;
import 'package:mind_metric/src/data/database/settings_dao.dart' as _i8;
import 'package:mind_metric/src/data/database/user_dao.dart' as _i24;
import 'package:mind_metric/src/utils/auth/auth_util.dart' as _i3;
import 'package:mind_metric/src/utils/error_logger.dart' as _i31;
import 'package:mind_metric/src/utils/file_downloader.dart' as _i32;
import 'package:mind_metric/src/utils/file_util.dart' as _i34;
import 'package:mind_metric/src/utils/network_validator.dart' as _i18;
import 'package:mind_metric/src/utils/sync/job_util.dart' as _i40;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i10;
import 'package:hive/hive.dart' as _i12;
import 'package:image_picker/image_picker.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i27;
import 'package:oauth2/oauth2.dart' as _i28;
import 'package:rxdart/rxdart.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthUtil_1 extends _i1.SmartFake implements _i3.AuthUtil {
  _FakeAuthUtil_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_2 extends _i1.SmartFake
    implements _i4.UserRepository {
  _FakeUserRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigRepository_3 extends _i1.SmartFake
    implements _i5.ConfigRepository {
  _FakeConfigRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteConfigRepository_4 extends _i1.SmartFake
    implements _i6.RemoteConfigRepository {
  _FakeRemoteConfigRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthTokenDao_5 extends _i1.SmartFake implements _i7.AuthTokenDao {
  _FakeAuthTokenDao_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsDao_6 extends _i1.SmartFake implements _i8.SettingsDao {
  _FakeSettingsDao_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSettingsDao_7 extends _i1.SmartFake
    implements _i9.AuthSettingsDao {
  _FakeAuthSettingsDao_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_8 extends _i1.SmartFake
    implements _i10.FlutterSecureStorage {
  _FakeFlutterSecureStorage_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_9 extends _i1.SmartFake implements _i11.Logger {
  _FakeLogger_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_10<E> extends _i1.SmartFake implements _i12.Box<E> {
  _FakeBox_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJobTimer_11 extends _i1.SmartFake implements _i13.JobTimer {
  _FakeJobTimer_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppDatabase_12 extends _i1.SmartFake implements _i14.AppDatabase {
  _FakeAppDatabase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_13 extends _i1.SmartFake
    implements _i15.AuthRepository {
  _FakeAuthRepository_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImagePicker_14 extends _i1.SmartFake implements _i16.ImagePicker {
  _FakeImagePicker_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_15 extends _i1.SmartFake implements _i17.File {
  _FakeFile_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_16 extends _i1.SmartFake implements _i10.IOSOptions {
  _FakeIOSOptions_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_17 extends _i1.SmartFake
    implements _i10.AndroidOptions {
  _FakeAndroidOptions_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_18 extends _i1.SmartFake implements _i10.LinuxOptions {
  _FakeLinuxOptions_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_19 extends _i1.SmartFake
    implements _i10.WindowsOptions {
  _FakeWindowsOptions_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_20 extends _i1.SmartFake implements _i10.WebOptions {
  _FakeWebOptions_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppleOptions_21 extends _i1.SmartFake implements _i10.AppleOptions {
  _FakeAppleOptions_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkValidator_22 extends _i1.SmartFake
    implements _i18.NetworkValidator {
  _FakeNetworkValidator_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJobManager_23 extends _i1.SmartFake implements _i19.JobManager {
  _FakeJobManager_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectivity_24 extends _i1.SmartFake implements _i20.Connectivity {
  _FakeConnectivity_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubject_25<T> extends _i1.SmartFake
    implements _i21.BehaviorSubject<T> {
  _FakeBehaviorSubject_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJobDao_26 extends _i1.SmartFake implements _i22.JobDao {
  _FakeJobDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJob_27 extends _i1.SmartFake implements _i14.Job {
  _FakeJob_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJobRepository_28 extends _i1.SmartFake
    implements _i23.JobRepository {
  _FakeJobRepository_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_29 extends _i1.SmartFake implements _i14.User {
  _FakeUser_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDao_30 extends _i1.SmartFake implements _i24.UserDao {
  _FakeUserDao_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserService_31 extends _i1.SmartFake implements _i25.UserService {
  _FakeUserService_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserMapper_32 extends _i1.SmartFake implements _i25.UserMapper {
  _FakeUserMapper_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i15.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get authServices => (super.noSuchMethod(
        Invocation.getter(#authServices),
        returnValue: _FakeAuthService_0(
          this,
          Invocation.getter(#authServices),
        ),
      ) as _i2.AuthService);

  @override
  _i3.AuthUtil get authUtil => (super.noSuchMethod(
        Invocation.getter(#authUtil),
        returnValue: _FakeAuthUtil_1(
          this,
          Invocation.getter(#authUtil),
        ),
      ) as _i3.AuthUtil);

  @override
  _i4.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_2(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i4.UserRepository);

  @override
  _i5.ConfigRepository get configRepository => (super.noSuchMethod(
        Invocation.getter(#configRepository),
        returnValue: _FakeConfigRepository_3(
          this,
          Invocation.getter(#configRepository),
        ),
      ) as _i5.ConfigRepository);

  @override
  _i6.RemoteConfigRepository get remoteConfigRepository => (super.noSuchMethod(
        Invocation.getter(#remoteConfigRepository),
        returnValue: _FakeRemoteConfigRepository_4(
          this,
          Invocation.getter(#remoteConfigRepository),
        ),
      ) as _i6.RemoteConfigRepository);

  @override
  _i7.AuthTokenDao get authTokenDao => (super.noSuchMethod(
        Invocation.getter(#authTokenDao),
        returnValue: _FakeAuthTokenDao_5(
          this,
          Invocation.getter(#authTokenDao),
        ),
      ) as _i7.AuthTokenDao);

  @override
  _i8.SettingsDao get settingsDao => (super.noSuchMethod(
        Invocation.getter(#settingsDao),
        returnValue: _FakeSettingsDao_6(
          this,
          Invocation.getter(#settingsDao),
        ),
      ) as _i8.SettingsDao);

  @override
  _i9.AuthSettingsDao get authSettingsDao => (super.noSuchMethod(
        Invocation.getter(#authSettingsDao),
        returnValue: _FakeAuthSettingsDao_7(
          this,
          Invocation.getter(#authSettingsDao),
        ),
      ) as _i9.AuthSettingsDao);

  @override
  _i10.FlutterSecureStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFlutterSecureStorage_8(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i10.FlutterSecureStorage);

  @override
  _i11.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_9(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i11.Logger);

  @override
  _i26.Future<_i14.User?> signIn(String? codeVerifier) => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [codeVerifier],
        ),
        returnValue: _i26.Future<_i14.User?>.value(),
      ) as _i26.Future<_i14.User?>);

  @override
  _i26.Future<String> getCodeVerifier() => (super.noSuchMethod(
        Invocation.method(
          #getCodeVerifier,
          [],
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getCodeVerifier,
            [],
          ),
        )),
      ) as _i26.Future<String>);

  @override
  _i26.Future<_i14.User?> saveCredentials(_i28.Credentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCredentials,
          [credentials],
        ),
        returnValue: _i26.Future<_i14.User?>.value(),
      ) as _i26.Future<_i14.User?>);

  @override
  _i26.Future<_i14.AuthToken?> getActiveToken() => (super.noSuchMethod(
        Invocation.method(
          #getActiveToken,
          [],
        ),
        returnValue: _i26.Future<_i14.AuthToken?>.value(),
      ) as _i26.Future<_i14.AuthToken?>);

  @override
  _i26.Future<bool> isSessionActive() => (super.noSuchMethod(
        Invocation.method(
          #isSessionActive,
          [],
        ),
        returnValue: _i26.Future<bool>.value(false),
      ) as _i26.Future<bool>);

  @override
  _i26.Future<bool> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i26.Future<bool>.value(false),
      ) as _i26.Future<bool>);

  @override
  _i26.Future<void> processAuthError() => (super.noSuchMethod(
        Invocation.method(
          #processAuthError,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> initRefreshAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #initRefreshAccessToken,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [AuthSettingsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSettingsDao extends _i1.Mock implements _i9.AuthSettingsDao {
  MockAuthSettingsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Future<_i12.Box<dynamic>> getBox() => (super.noSuchMethod(
        Invocation.method(
          #getBox,
          [],
        ),
        returnValue: _i26.Future<_i12.Box<dynamic>>.value(_FakeBox_10<dynamic>(
          this,
          Invocation.method(
            #getBox,
            [],
          ),
        )),
      ) as _i26.Future<_i12.Box<dynamic>>);

  @override
  _i26.Future<void> saveLastTokenRefresh(DateTime? data) => (super.noSuchMethod(
        Invocation.method(
          #saveLastTokenRefresh,
          [data],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<DateTime?> getLastTokenRefresh() => (super.noSuchMethod(
        Invocation.method(
          #getLastTokenRefresh,
          [],
        ),
        returnValue: _i26.Future<DateTime?>.value(),
      ) as _i26.Future<DateTime?>);

  @override
  _i26.Future<void> saveCodeVerifier(String? data) => (super.noSuchMethod(
        Invocation.method(
          #saveCodeVerifier,
          [data],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<String?> getCodeVerifier() => (super.noSuchMethod(
        Invocation.method(
          #getCodeVerifier,
          [],
        ),
        returnValue: _i26.Future<String?>.value(),
      ) as _i26.Future<String?>);

  @override
  _i26.Future<void> saveOAuthCredential(String? data) => (super.noSuchMethod(
        Invocation.method(
          #saveOAuthCredential,
          [data],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<String?> getOAuthCredential() => (super.noSuchMethod(
        Invocation.method(
          #getOAuthCredential,
          [],
        ),
        returnValue: _i26.Future<String?>.value(),
      ) as _i26.Future<String?>);

  @override
  _i26.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [AuthUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUtil extends _i1.Mock implements _i3.AuthUtil {
  MockAuthUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.JobTimer get jobTimer => (super.noSuchMethod(
        Invocation.getter(#jobTimer),
        returnValue: _FakeJobTimer_11(
          this,
          Invocation.getter(#jobTimer),
        ),
      ) as _i13.JobTimer);

  @override
  _i10.FlutterSecureStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFlutterSecureStorage_8(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i10.FlutterSecureStorage);

  @override
  _i14.AppDatabase get appDatabase => (super.noSuchMethod(
        Invocation.getter(#appDatabase),
        returnValue: _FakeAppDatabase_12(
          this,
          Invocation.getter(#appDatabase),
        ),
      ) as _i14.AppDatabase);

  @override
  _i8.SettingsDao get settingsDao => (super.noSuchMethod(
        Invocation.getter(#settingsDao),
        returnValue: _FakeSettingsDao_6(
          this,
          Invocation.getter(#settingsDao),
        ),
      ) as _i8.SettingsDao);

  @override
  _i9.AuthSettingsDao get authSettingsDao => (super.noSuchMethod(
        Invocation.getter(#authSettingsDao),
        returnValue: _FakeAuthSettingsDao_7(
          this,
          Invocation.getter(#authSettingsDao),
        ),
      ) as _i9.AuthSettingsDao);

  @override
  _i26.Future<dynamic> clearData() => (super.noSuchMethod(
        Invocation.method(
          #clearData,
          [],
        ),
        returnValue: _i26.Future<dynamic>.value(),
      ) as _i26.Future<dynamic>);
}

/// A class which mocks [ConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigRepository extends _i1.Mock implements _i5.ConfigRepository {
  MockConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get restBaseUrlDev => (super.noSuchMethod(
        Invocation.getter(#restBaseUrlDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restBaseUrlDev),
        ),
      ) as String);

  @override
  String get identityServerUrlDev => (super.noSuchMethod(
        Invocation.getter(#identityServerUrlDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#identityServerUrlDev),
        ),
      ) as String);

  @override
  String get authRedirectUriDev => (super.noSuchMethod(
        Invocation.getter(#authRedirectUriDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#authRedirectUriDev),
        ),
      ) as String);

  @override
  String get logoutRedirectUriDev => (super.noSuchMethod(
        Invocation.getter(#logoutRedirectUriDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#logoutRedirectUriDev),
        ),
      ) as String);

  @override
  String get restBaseUrlQA => (super.noSuchMethod(
        Invocation.getter(#restBaseUrlQA),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restBaseUrlQA),
        ),
      ) as String);

  @override
  String get authRedirectUriQA => (super.noSuchMethod(
        Invocation.getter(#authRedirectUriQA),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#authRedirectUriQA),
        ),
      ) as String);

  @override
  String get identityServerUrlQA => (super.noSuchMethod(
        Invocation.getter(#identityServerUrlQA),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#identityServerUrlQA),
        ),
      ) as String);

  @override
  String get restBaseUrlStaging => (super.noSuchMethod(
        Invocation.getter(#restBaseUrlStaging),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restBaseUrlStaging),
        ),
      ) as String);

  @override
  String get authRedirectUriStaging => (super.noSuchMethod(
        Invocation.getter(#authRedirectUriStaging),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#authRedirectUriStaging),
        ),
      ) as String);

  @override
  String get identityServerUrlStaging => (super.noSuchMethod(
        Invocation.getter(#identityServerUrlStaging),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#identityServerUrlStaging),
        ),
      ) as String);

  @override
  String get restBaseUrlProd => (super.noSuchMethod(
        Invocation.getter(#restBaseUrlProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restBaseUrlProd),
        ),
      ) as String);

  @override
  String get identityServerUrlProd => (super.noSuchMethod(
        Invocation.getter(#identityServerUrlProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#identityServerUrlProd),
        ),
      ) as String);

  @override
  String get authRedirectUriProd => (super.noSuchMethod(
        Invocation.getter(#authRedirectUriProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#authRedirectUriProd),
        ),
      ) as String);

  @override
  String get logoutRedirectUriProd => (super.noSuchMethod(
        Invocation.getter(#logoutRedirectUriProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#logoutRedirectUriProd),
        ),
      ) as String);

  @override
  String get tenantIDDev => (super.noSuchMethod(
        Invocation.getter(#tenantIDDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#tenantIDDev),
        ),
      ) as String);

  @override
  String get clientIDDev => (super.noSuchMethod(
        Invocation.getter(#clientIDDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientIDDev),
        ),
      ) as String);

  @override
  String get clientSecretDev => (super.noSuchMethod(
        Invocation.getter(#clientSecretDev),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientSecretDev),
        ),
      ) as String);

  @override
  String get tenantIDQA => (super.noSuchMethod(
        Invocation.getter(#tenantIDQA),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#tenantIDQA),
        ),
      ) as String);

  @override
  String get clientIDQA => (super.noSuchMethod(
        Invocation.getter(#clientIDQA),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientIDQA),
        ),
      ) as String);

  @override
  String get clientSecretQA => (super.noSuchMethod(
        Invocation.getter(#clientSecretQA),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientSecretQA),
        ),
      ) as String);

  @override
  String get tenantIDStaging => (super.noSuchMethod(
        Invocation.getter(#tenantIDStaging),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#tenantIDStaging),
        ),
      ) as String);

  @override
  String get clientIDStaging => (super.noSuchMethod(
        Invocation.getter(#clientIDStaging),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientIDStaging),
        ),
      ) as String);

  @override
  String get clientSecretStaging => (super.noSuchMethod(
        Invocation.getter(#clientSecretStaging),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientSecretStaging),
        ),
      ) as String);

  @override
  String get tenantIDProd => (super.noSuchMethod(
        Invocation.getter(#tenantIDProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#tenantIDProd),
        ),
      ) as String);

  @override
  String get clientIDProd => (super.noSuchMethod(
        Invocation.getter(#clientIDProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientIDProd),
        ),
      ) as String);

  @override
  String get clientSecretProd => (super.noSuchMethod(
        Invocation.getter(#clientSecretProd),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientSecretProd),
        ),
      ) as String);

  @override
  String get restHeadsUrl => (super.noSuchMethod(
        Invocation.getter(#restHeadsUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restHeadsUrl),
        ),
      ) as String);

  @override
  String get restEmployeeBasicDetailsUrl => (super.noSuchMethod(
        Invocation.getter(#restEmployeeBasicDetailsUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restEmployeeBasicDetailsUrl),
        ),
      ) as String);

  @override
  String get restLeaveEntitlementUrl => (super.noSuchMethod(
        Invocation.getter(#restLeaveEntitlementUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restLeaveEntitlementUrl),
        ),
      ) as String);

  @override
  String get restLeaveRequestListUrl => (super.noSuchMethod(
        Invocation.getter(#restLeaveRequestListUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restLeaveRequestListUrl),
        ),
      ) as String);

  @override
  int get iOSMinVersionCodeDev => (super.noSuchMethod(
        Invocation.getter(#iOSMinVersionCodeDev),
        returnValue: 0,
      ) as int);

  @override
  int get iOSMinVersionCodeQA => (super.noSuchMethod(
        Invocation.getter(#iOSMinVersionCodeQA),
        returnValue: 0,
      ) as int);

  @override
  int get iOSMinVersionCodeStaging => (super.noSuchMethod(
        Invocation.getter(#iOSMinVersionCodeStaging),
        returnValue: 0,
      ) as int);

  @override
  int get iOSMinVersionCodeProd => (super.noSuchMethod(
        Invocation.getter(#iOSMinVersionCodeProd),
        returnValue: 0,
      ) as int);

  @override
  int get iOSLatestVersionCodeDev => (super.noSuchMethod(
        Invocation.getter(#iOSLatestVersionCodeDev),
        returnValue: 0,
      ) as int);

  @override
  int get iOSLatestVersionCodeQA => (super.noSuchMethod(
        Invocation.getter(#iOSLatestVersionCodeQA),
        returnValue: 0,
      ) as int);

  @override
  int get iOSLatestVersionCodeStaging => (super.noSuchMethod(
        Invocation.getter(#iOSLatestVersionCodeStaging),
        returnValue: 0,
      ) as int);

  @override
  int get iOSLatestVersionCodeProd => (super.noSuchMethod(
        Invocation.getter(#iOSLatestVersionCodeProd),
        returnValue: 0,
      ) as int);

  @override
  int get androidMinVersionCodeDev => (super.noSuchMethod(
        Invocation.getter(#androidMinVersionCodeDev),
        returnValue: 0,
      ) as int);

  @override
  int get androidMinVersionCodeQA => (super.noSuchMethod(
        Invocation.getter(#androidMinVersionCodeQA),
        returnValue: 0,
      ) as int);

  @override
  int get androidMinVersionCodeStaging => (super.noSuchMethod(
        Invocation.getter(#androidMinVersionCodeStaging),
        returnValue: 0,
      ) as int);

  @override
  int get androidMinVersionCodeProd => (super.noSuchMethod(
        Invocation.getter(#androidMinVersionCodeProd),
        returnValue: 0,
      ) as int);

  @override
  int get androidLatestVersionCodeDev => (super.noSuchMethod(
        Invocation.getter(#androidLatestVersionCodeDev),
        returnValue: 0,
      ) as int);

  @override
  int get androidLatestVersionCodeQA => (super.noSuchMethod(
        Invocation.getter(#androidLatestVersionCodeQA),
        returnValue: 0,
      ) as int);

  @override
  int get androidLatestVersionCodeStaging => (super.noSuchMethod(
        Invocation.getter(#androidLatestVersionCodeStaging),
        returnValue: 0,
      ) as int);

  @override
  int get androidLatestVersionCodeProd => (super.noSuchMethod(
        Invocation.getter(#androidLatestVersionCodeProd),
        returnValue: 0,
      ) as int);

  @override
  String get immediateUpdateTitle => (super.noSuchMethod(
        Invocation.getter(#immediateUpdateTitle),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#immediateUpdateTitle),
        ),
      ) as String);

  @override
  String get immediateUpdateMessage => (super.noSuchMethod(
        Invocation.getter(#immediateUpdateMessage),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#immediateUpdateMessage),
        ),
      ) as String);

  @override
  String get flexibleUpdateTitle => (super.noSuchMethod(
        Invocation.getter(#flexibleUpdateTitle),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#flexibleUpdateTitle),
        ),
      ) as String);

  @override
  String get flexibleUpdateMessage => (super.noSuchMethod(
        Invocation.getter(#flexibleUpdateMessage),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#flexibleUpdateMessage),
        ),
      ) as String);

  @override
  String get googleAPIKeyAndroid => (super.noSuchMethod(
        Invocation.getter(#googleAPIKeyAndroid),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#googleAPIKeyAndroid),
        ),
      ) as String);

  @override
  String get googleAPIKeyIOS => (super.noSuchMethod(
        Invocation.getter(#googleAPIKeyIOS),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#googleAPIKeyIOS),
        ),
      ) as String);

  @override
  String get googleAPIKeyBrowser => (super.noSuchMethod(
        Invocation.getter(#googleAPIKeyBrowser),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#googleAPIKeyBrowser),
        ),
      ) as String);

  @override
  String get restRemoteConfigUrl => (super.noSuchMethod(
        Invocation.getter(#restRemoteConfigUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restRemoteConfigUrl),
        ),
      ) as String);

  @override
  String get restRemoteConfigProviderUrl => (super.noSuchMethod(
        Invocation.getter(#restRemoteConfigProviderUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restRemoteConfigProviderUrl),
        ),
      ) as String);

  @override
  String get synergyProxy => (super.noSuchMethod(
        Invocation.getter(#synergyProxy),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#synergyProxy),
        ),
      ) as String);

  @override
  void setFirebaseRemoteConfig(_i29.FirebaseRemoteConfig? config) =>
      super.noSuchMethod(
        Invocation.method(
          #setFirebaseRemoteConfig,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i26.Future<void> initConfig() => (super.noSuchMethod(
        Invocation.method(
          #initConfig,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> syncConfig() => (super.noSuchMethod(
        Invocation.method(
          #syncConfig,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  bool isInitialFetchCompleted() => (super.noSuchMethod(
        Invocation.method(
          #isInitialFetchCompleted,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i26.Future<void> updateDefaultConfig(Map<String, dynamic>? defaultConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDefaultConfig,
          [defaultConfig],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i20.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Stream<List<_i30.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i26.Stream<List<_i30.ConnectivityResult>>.empty(),
      ) as _i26.Stream<List<_i30.ConnectivityResult>>);

  @override
  _i26.Future<List<_i30.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i26.Future<List<_i30.ConnectivityResult>>.value(
            <_i30.ConnectivityResult>[]),
      ) as _i26.Future<List<_i30.ConnectivityResult>>);
}

/// A class which mocks [ErrorLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorLogger extends _i1.Mock implements _i31.ErrorLogger {
  MockErrorLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void recordError({
    dynamic exception,
    StackTrace? stackTrace,
    bool? fatal = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordError,
          [],
          {
            #exception: exception,
            #stackTrace: stackTrace,
            #fatal: fatal,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FileDownloader].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileDownloader extends _i1.Mock implements _i32.FileDownloader {
  MockFileDownloader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_13(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i15.AuthRepository);

  @override
  _i26.Future<String> downloadForFileInfo({
    required _i33.FileInfo? fileInfo,
    String? pathPrefix,
    bool? isDatePrefixRequired = true,
    bool? isAccessTokenRequired = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadForFileInfo,
          [],
          {
            #fileInfo: fileInfo,
            #pathPrefix: pathPrefix,
            #isDatePrefixRequired: isDatePrefixRequired,
            #isAccessTokenRequired: isAccessTokenRequired,
          },
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #downloadForFileInfo,
            [],
            {
              #fileInfo: fileInfo,
              #pathPrefix: pathPrefix,
              #isDatePrefixRequired: isDatePrefixRequired,
              #isAccessTokenRequired: isAccessTokenRequired,
            },
          ),
        )),
      ) as _i26.Future<String>);

  @override
  _i26.Future<void> download({
    required String? downloadUrl,
    required String? savePath,
    bool? isAccessTokenRequired = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
          {
            #downloadUrl: downloadUrl,
            #savePath: savePath,
            #isAccessTokenRequired: isAccessTokenRequired,
          },
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [FileUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileUtil extends _i1.Mock implements _i34.FileUtil {
  MockFileUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.ImagePicker get imagePicker => (super.noSuchMethod(
        Invocation.getter(#imagePicker),
        returnValue: _FakeImagePicker_14(
          this,
          Invocation.getter(#imagePicker),
        ),
      ) as _i16.ImagePicker);

  @override
  _i26.Future<String> getApplicationPath() => (super.noSuchMethod(
        Invocation.method(
          #getApplicationPath,
          [],
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getApplicationPath,
            [],
          ),
        )),
      ) as _i26.Future<String>);

  @override
  _i26.Future<String> getApplicationTempPath() => (super.noSuchMethod(
        Invocation.method(
          #getApplicationTempPath,
          [],
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getApplicationTempPath,
            [],
          ),
        )),
      ) as _i26.Future<String>);

  @override
  _i26.Future<String> getExternalPath() => (super.noSuchMethod(
        Invocation.method(
          #getExternalPath,
          [],
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getExternalPath,
            [],
          ),
        )),
      ) as _i26.Future<String>);

  @override
  _i26.Future<String> getDownloadPath() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadPath,
          [],
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getDownloadPath,
            [],
          ),
        )),
      ) as _i26.Future<String>);

  @override
  String getPathPrefix({
    required String? cdcNumber,
    String? module,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPathPrefix,
          [],
          {
            #cdcNumber: cdcNumber,
            #module: module,
          },
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #getPathPrefix,
            [],
            {
              #cdcNumber: cdcNumber,
              #module: module,
            },
          ),
        ),
      ) as String);

  @override
  _i26.Future<void> createDir(String? basePath) => (super.noSuchMethod(
        Invocation.method(
          #createDir,
          [basePath],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> createDirectoryFromPath(String? newPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDirectoryFromPath,
          [newPath],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<String> absolutePath(
    String? relativePath, {
    bool? useCache = false,
    bool? useExternal = false,
    bool? useDownload = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #absolutePath,
          [relativePath],
          {
            #useCache: useCache,
            #useExternal: useExternal,
            #useDownload: useDownload,
          },
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #absolutePath,
            [relativePath],
            {
              #useCache: useCache,
              #useExternal: useExternal,
              #useDownload: useDownload,
            },
          ),
        )),
      ) as _i26.Future<String>);

  @override
  _i26.Future<_i17.File> moveFile(
    _i17.File? sourceFile,
    String? newPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFile,
          [
            sourceFile,
            newPath,
          ],
        ),
        returnValue: _i26.Future<_i17.File>.value(_FakeFile_15(
          this,
          Invocation.method(
            #moveFile,
            [
              sourceFile,
              newPath,
            ],
          ),
        )),
      ) as _i26.Future<_i17.File>);

  @override
  _i26.Future<_i17.File> copyFile(
    _i17.File? sourceFile,
    String? newPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyFile,
          [
            sourceFile,
            newPath,
          ],
        ),
        returnValue: _i26.Future<_i17.File>.value(_FakeFile_15(
          this,
          Invocation.method(
            #copyFile,
            [
              sourceFile,
              newPath,
            ],
          ),
        )),
      ) as _i26.Future<_i17.File>);

  @override
  _i26.Future<String> getFileSize(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [path],
        ),
        returnValue: _i26.Future<String>.value(_i27.dummyValue<String>(
          this,
          Invocation.method(
            #getFileSize,
            [path],
          ),
        )),
      ) as _i26.Future<String>);

  @override
  String getContentType(_i17.File? file) => (super.noSuchMethod(
        Invocation.method(
          #getContentType,
          [file],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #getContentType,
            [file],
          ),
        ),
      ) as String);

  @override
  String getContentTypeFromXFile(_i35.XFile? file) => (super.noSuchMethod(
        Invocation.method(
          #getContentTypeFromXFile,
          [file],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #getContentTypeFromXFile,
            [file],
          ),
        ),
      ) as String);

  @override
  String getProcessedFileUri(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getProcessedFileUri,
          [path],
        ),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.method(
            #getProcessedFileUri,
            [path],
          ),
        ),
      ) as String);

  @override
  _i26.Future<_i17.File?> openDocumentPickerForMobile(
    _i36.BuildContext? context, {
    bool? isImageOnly = false,
    bool? isAudioOnly = false,
    bool? isPdfOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openDocumentPickerForMobile,
          [context],
          {
            #isImageOnly: isImageOnly,
            #isAudioOnly: isAudioOnly,
            #isPdfOnly: isPdfOnly,
          },
        ),
        returnValue: _i26.Future<_i17.File?>.value(),
      ) as _i26.Future<_i17.File?>);

  @override
  _i26.Future<_i35.XFile?> openDocumentPickerXFile(
    _i36.BuildContext? context, {
    bool? isImageOnly = false,
    bool? isAudioOnly = false,
    bool? isPdfOnly = false,
    bool? useFileSelectorOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openDocumentPickerXFile,
          [context],
          {
            #isImageOnly: isImageOnly,
            #isAudioOnly: isAudioOnly,
            #isPdfOnly: isPdfOnly,
            #useFileSelectorOnly: useFileSelectorOnly,
          },
        ),
        returnValue: _i26.Future<_i35.XFile?>.value(),
      ) as _i26.Future<_i35.XFile?>);

  @override
  List<_i35.XTypeGroup> getTypeGroups(
    bool? isImageOnly,
    bool? isAudioOnly,
    bool? isPdfOnly,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTypeGroups,
          [
            isImageOnly,
            isAudioOnly,
            isPdfOnly,
          ],
        ),
        returnValue: <_i35.XTypeGroup>[],
      ) as List<_i35.XTypeGroup>);

  @override
  _i26.Future<List<_i35.XFile>> pickDocumentList({
    bool? isImageOnly = false,
    bool? isAudioOnly = false,
    bool? isPdfOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickDocumentList,
          [],
          {
            #isImageOnly: isImageOnly,
            #isAudioOnly: isAudioOnly,
            #isPdfOnly: isPdfOnly,
          },
        ),
        returnValue: _i26.Future<List<_i35.XFile>>.value(<_i35.XFile>[]),
      ) as _i26.Future<List<_i35.XFile>>);
}

/// A class which mocks [Flavor].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavor extends _i1.Mock implements _i37.Flavor {
  MockFlavor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  int get iOSMinVersionCode => (super.noSuchMethod(
        Invocation.getter(#iOSMinVersionCode),
        returnValue: 0,
      ) as int);

  @override
  int get iOSLatestVersionCode => (super.noSuchMethod(
        Invocation.getter(#iOSLatestVersionCode),
        returnValue: 0,
      ) as int);

  @override
  int get androidMinVersionCode => (super.noSuchMethod(
        Invocation.getter(#androidMinVersionCode),
        returnValue: 0,
      ) as int);

  @override
  int get androidLatestVersionCode => (super.noSuchMethod(
        Invocation.getter(#androidLatestVersionCode),
        returnValue: 0,
      ) as int);

  @override
  String get restApiVersion => (super.noSuchMethod(
        Invocation.getter(#restApiVersion),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restApiVersion),
        ),
      ) as String);

  @override
  String get restBaseUrl => (super.noSuchMethod(
        Invocation.getter(#restBaseUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#restBaseUrl),
        ),
      ) as String);

  @override
  String get identityServerBaseUrl => (super.noSuchMethod(
        Invocation.getter(#identityServerBaseUrl),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#identityServerBaseUrl),
        ),
      ) as String);

  @override
  String get authRedirectUri => (super.noSuchMethod(
        Invocation.getter(#authRedirectUri),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#authRedirectUri),
        ),
      ) as String);

  @override
  String get tenantID => (super.noSuchMethod(
        Invocation.getter(#tenantID),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#tenantID),
        ),
      ) as String);

  @override
  String get clientID => (super.noSuchMethod(
        Invocation.getter(#clientID),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientID),
        ),
      ) as String);

  @override
  String get clientSecret => (super.noSuchMethod(
        Invocation.getter(#clientSecret),
        returnValue: _i27.dummyValue<String>(
          this,
          Invocation.getter(#clientSecret),
        ),
      ) as String);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i10.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_16(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i10.IOSOptions);

  @override
  _i10.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_17(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i10.AndroidOptions);

  @override
  _i10.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_18(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i10.LinuxOptions);

  @override
  _i10.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_19(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i10.WindowsOptions);

  @override
  _i10.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_20(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i10.WebOptions);

  @override
  _i10.AppleOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeAppleOptions_21(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i10.AppleOptions);

  @override
  Map<String, List<_i38.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
        Invocation.getter(#getListeners),
        returnValue: <String, List<_i38.ValueChanged<String?>>>{},
      ) as Map<String, List<_i38.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i38.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i38.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i26.Future<void> write({
    required String? key,
    required String? value,
    _i10.AppleOptions? iOptions,
    _i10.AndroidOptions? aOptions,
    _i10.LinuxOptions? lOptions,
    _i10.WebOptions? webOptions,
    _i10.AppleOptions? mOptions,
    _i10.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<String?> read({
    required String? key,
    _i10.AppleOptions? iOptions,
    _i10.AndroidOptions? aOptions,
    _i10.LinuxOptions? lOptions,
    _i10.WebOptions? webOptions,
    _i10.AppleOptions? mOptions,
    _i10.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i26.Future<String?>.value(),
      ) as _i26.Future<String?>);

  @override
  _i26.Future<bool> containsKey({
    required String? key,
    _i10.AppleOptions? iOptions,
    _i10.AndroidOptions? aOptions,
    _i10.LinuxOptions? lOptions,
    _i10.WebOptions? webOptions,
    _i10.AppleOptions? mOptions,
    _i10.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i26.Future<bool>.value(false),
      ) as _i26.Future<bool>);

  @override
  _i26.Future<void> delete({
    required String? key,
    _i10.AppleOptions? iOptions,
    _i10.AndroidOptions? aOptions,
    _i10.LinuxOptions? lOptions,
    _i10.WebOptions? webOptions,
    _i10.AppleOptions? mOptions,
    _i10.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<Map<String, String>> readAll({
    _i10.AppleOptions? iOptions,
    _i10.AndroidOptions? aOptions,
    _i10.LinuxOptions? lOptions,
    _i10.WebOptions? webOptions,
    _i10.AppleOptions? mOptions,
    _i10.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i26.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i26.Future<Map<String, String>>);

  @override
  _i26.Future<void> deleteAll({
    _i10.AppleOptions? iOptions,
    _i10.AndroidOptions? aOptions,
    _i10.LinuxOptions? lOptions,
    _i10.WebOptions? webOptions,
    _i10.AppleOptions? mOptions,
    _i10.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i26.Future<bool?>.value(),
      ) as _i26.Future<bool?>);
}

/// A class which mocks [JobConnectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobConnectivity extends _i1.Mock implements _i39.JobConnectivity {
  MockJobConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.JobTimer get jobTimer => (super.noSuchMethod(
        Invocation.getter(#jobTimer),
        returnValue: _FakeJobTimer_11(
          this,
          Invocation.getter(#jobTimer),
        ),
      ) as _i13.JobTimer);

  @override
  _i18.NetworkValidator get networkValidator => (super.noSuchMethod(
        Invocation.getter(#networkValidator),
        returnValue: _FakeNetworkValidator_22(
          this,
          Invocation.getter(#networkValidator),
        ),
      ) as _i18.NetworkValidator);

  @override
  _i19.JobManager get jobManager => (super.noSuchMethod(
        Invocation.getter(#jobManager),
        returnValue: _FakeJobManager_23(
          this,
          Invocation.getter(#jobManager),
        ),
      ) as _i19.JobManager);

  @override
  _i15.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_13(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i15.AuthRepository);

  @override
  _i20.Connectivity get connectivity => (super.noSuchMethod(
        Invocation.getter(#connectivity),
        returnValue: _FakeConnectivity_24(
          this,
          Invocation.getter(#connectivity),
        ),
      ) as _i20.Connectivity);

  @override
  _i26.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [JobManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobManager extends _i1.Mock implements _i19.JobManager {
  MockJobManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.BehaviorSubject<bool> get isSyncingSubject => (super.noSuchMethod(
        Invocation.getter(#isSyncingSubject),
        returnValue: _FakeBehaviorSubject_25<bool>(
          this,
          Invocation.getter(#isSyncingSubject),
        ),
      ) as _i21.BehaviorSubject<bool>);

  @override
  _i26.Stream<bool> get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: _i26.Stream<bool>.empty(),
      ) as _i26.Stream<bool>);

  @override
  _i26.Future<void> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> syncJob(_i14.Job? job) => (super.noSuchMethod(
        Invocation.method(
          #syncJob,
          [job],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [JobRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobRepository extends _i1.Mock implements _i23.JobRepository {
  MockJobRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.JobDao get dao => (super.noSuchMethod(
        Invocation.getter(#dao),
        returnValue: _FakeJobDao_26(
          this,
          Invocation.getter(#dao),
        ),
      ) as _i22.JobDao);

  @override
  set dao(_i22.JobDao? value) => super.noSuchMethod(
        Invocation.setter(
          #dao,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i26.Future<void> createSyncJob(_i14.Job? job) => (super.noSuchMethod(
        Invocation.method(
          #createSyncJob,
          [job],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<List<_i14.Job>> getNextJobs(
    String? userId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextJobs,
          [
            userId,
            limit,
          ],
        ),
        returnValue: _i26.Future<List<_i14.Job>>.value(<_i14.Job>[]),
      ) as _i26.Future<List<_i14.Job>>);

  @override
  _i26.Stream<String?> watchCurrentStatus(
    String? jobType,
    String? recordId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchCurrentStatus,
          [
            jobType,
            recordId,
          ],
        ),
        returnValue: _i26.Stream<String?>.empty(),
      ) as _i26.Stream<String?>);

  @override
  _i26.Future<_i14.Job?> getJob(
    String? type,
    String? recordId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJob,
          [
            type,
            recordId,
          ],
        ),
        returnValue: _i26.Future<_i14.Job?>.value(),
      ) as _i26.Future<_i14.Job?>);

  @override
  _i26.Future<_i14.Job> getJobById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getJobById,
          [id],
        ),
        returnValue: _i26.Future<_i14.Job>.value(_FakeJob_27(
          this,
          Invocation.method(
            #getJobById,
            [id],
          ),
        )),
      ) as _i26.Future<_i14.Job>);

  @override
  _i26.Future<_i14.Job?> getJobByType(
    String? jobType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobByType,
          [
            jobType,
            userId,
          ],
        ),
        returnValue: _i26.Future<_i14.Job?>.value(),
      ) as _i26.Future<_i14.Job?>);

  @override
  _i26.Stream<List<_i14.Job>> watchJobListByType(
    String? jobType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchJobListByType,
          [
            jobType,
            userId,
          ],
        ),
        returnValue: _i26.Stream<List<_i14.Job>>.empty(),
      ) as _i26.Stream<List<_i14.Job>>);

  @override
  _i26.Future<List<_i14.Job>> getJobListByType(
    String? jobType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobListByType,
          [
            jobType,
            userId,
          ],
        ),
        returnValue: _i26.Future<List<_i14.Job>>.value(<_i14.Job>[]),
      ) as _i26.Future<List<_i14.Job>>);

  @override
  _i26.Stream<List<_i14.Job>> watchJobListByTypeList(
    List<String>? jobTypeList,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchJobListByTypeList,
          [
            jobTypeList,
            userId,
          ],
        ),
        returnValue: _i26.Stream<List<_i14.Job>>.empty(),
      ) as _i26.Stream<List<_i14.Job>>);

  @override
  _i26.Future<void> deleteJobById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJobById,
          [id],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> markJobAsFailed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markJobAsFailed,
          [id],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> updateJobStatus(
    String? jobId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJobStatus,
          [
            jobId,
            status,
          ],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<void> markFailedJobsAsPending(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markFailedJobsAsPending,
          [userId],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<int> getRemainingJobCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getRemainingJobCount,
          [userId],
        ),
        returnValue: _i26.Future<int>.value(0),
      ) as _i26.Future<int>);

  @override
  _i26.Future<int> getRemainingJobCountByStatus({
    required String? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemainingJobCountByStatus,
          [],
          {
            #userId: userId,
            #status: status,
          },
        ),
        returnValue: _i26.Future<int>.value(0),
      ) as _i26.Future<int>);

  @override
  _i26.Future<void> updateAllJobStatus({
    required String? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAllJobStatus,
          [],
          {
            #userId: userId,
            #status: status,
          },
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [JobTimer].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobTimer extends _i1.Mock implements _i13.JobTimer {
  MockJobTimer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set timer(_i26.Timer? value) => super.noSuchMethod(
        Invocation.setter(
          #timer,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i26.Future<void> startTimer(
    bool? isSessionActive, {
    int? repeatInterval = 60,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTimer,
          [isSessionActive],
          {#repeatInterval: repeatInterval},
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  void stopTimer() => super.noSuchMethod(
        Invocation.method(
          #stopTimer,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [JobUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobUtils extends _i1.Mock implements _i40.JobUtils {
  MockJobUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.JobRepository get jobRepository => (super.noSuchMethod(
        Invocation.getter(#jobRepository),
        returnValue: _FakeJobRepository_28(
          this,
          Invocation.getter(#jobRepository),
        ),
      ) as _i23.JobRepository);

  @override
  _i19.JobManager get jobManager => (super.noSuchMethod(
        Invocation.getter(#jobManager),
        returnValue: _FakeJobManager_23(
          this,
          Invocation.getter(#jobManager),
        ),
      ) as _i19.JobManager);

  @override
  _i26.Future<void> validateNoPendingJob(
    String? type,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateNoPendingJob,
          [
            type,
            userId,
          ],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<List<_i14.Job>> getPendingJobListByType(
    String? type,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingJobListByType,
          [
            type,
            userId,
          ],
        ),
        returnValue: _i26.Future<List<_i14.Job>>.value(<_i14.Job>[]),
      ) as _i26.Future<List<_i14.Job>>);

  @override
  _i26.Future<bool> scheduleJob(
    String? type,
    String? userId,
    String? recordId, {
    int? priority = 1,
    String? status = 'pending',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleJob,
          [
            type,
            userId,
            recordId,
          ],
          {
            #priority: priority,
            #status: status,
          },
        ),
        returnValue: _i26.Future<bool>.value(false),
      ) as _i26.Future<bool>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void login(_i14.User? user) => super.noSuchMethod(
        Invocation.method(
          #login,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logout() => super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCurrentScreen(String? name) => super.noSuchMethod(
        Invocation.method(
          #setCurrentScreen,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i26.Future<dynamic> log(
    String? eventName,
    Map<String, dynamic>? eventParams, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #log,
          [
            eventName,
            eventParams,
          ],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i26.Future<dynamic>.value(),
      ) as _i26.Future<dynamic>);

  @override
  void setUserID(String? id) => super.noSuchMethod(
        Invocation.method(
          #setUserID,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsDao extends _i1.Mock implements _i8.SettingsDao {
  MockSettingsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Future<_i12.Box<dynamic>> getBox() => (super.noSuchMethod(
        Invocation.method(
          #getBox,
          [],
        ),
        returnValue: _i26.Future<_i12.Box<dynamic>>.value(_FakeBox_10<dynamic>(
          this,
          Invocation.method(
            #getBox,
            [],
          ),
        )),
      ) as _i26.Future<_i12.Box<dynamic>>);

  @override
  _i26.Future<void> setSecurityEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setSecurityEnabled,
          [value],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<bool> isSecurityEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isSecurityEnabled,
          [],
        ),
        returnValue: _i26.Future<bool>.value(false),
      ) as _i26.Future<bool>);

  @override
  _i26.Future<void> setInitialFetchCompleted(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInitialFetchCompleted,
          [value],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<bool> isInitialFetchCompleted() => (super.noSuchMethod(
        Invocation.method(
          #isInitialFetchCompleted,
          [],
        ),
        returnValue: _i26.Future<bool>.value(false),
      ) as _i26.Future<bool>);

  @override
  _i26.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}

/// A class which mocks [UserMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserMapper extends _i1.Mock implements _i25.UserMapper {
  MockUserMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.User fromNetworkJson(Map<String, dynamic>? json) => (super.noSuchMethod(
        Invocation.method(
          #fromNetworkJson,
          [json],
        ),
        returnValue: _FakeUser_29(
          this,
          Invocation.method(
            #fromNetworkJson,
            [json],
          ),
        ),
      ) as _i14.User);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.UserDao get userDao => (super.noSuchMethod(
        Invocation.getter(#userDao),
        returnValue: _FakeUserDao_30(
          this,
          Invocation.getter(#userDao),
        ),
      ) as _i24.UserDao);

  @override
  _i25.UserService get networkProvider => (super.noSuchMethod(
        Invocation.getter(#networkProvider),
        returnValue: _FakeUserService_31(
          this,
          Invocation.getter(#networkProvider),
        ),
      ) as _i25.UserService);

  @override
  _i25.UserMapper get userMapper => (super.noSuchMethod(
        Invocation.getter(#userMapper),
        returnValue: _FakeUserMapper_32(
          this,
          Invocation.getter(#userMapper),
        ),
      ) as _i25.UserMapper);

  @override
  _i26.Future<_i14.User> getUser(_i14.AuthToken? authToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [authToken],
        ),
        returnValue: _i26.Future<_i14.User>.value(_FakeUser_29(
          this,
          Invocation.method(
            #getUser,
            [authToken],
          ),
        )),
      ) as _i26.Future<_i14.User>);

  @override
  _i26.Future<_i14.User?> userById(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #userById,
          [userId],
        ),
        returnValue: _i26.Future<_i14.User?>.value(),
      ) as _i26.Future<_i14.User?>);

  @override
  _i26.Future<void> saveUser(_i14.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);

  @override
  _i26.Future<_i14.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i26.Future<_i14.User?>.value(),
      ) as _i26.Future<_i14.User?>);

  @override
  _i26.Future<_i14.User> getActiveUser() => (super.noSuchMethod(
        Invocation.method(
          #getActiveUser,
          [],
        ),
        returnValue: _i26.Future<_i14.User>.value(_FakeUser_29(
          this,
          Invocation.method(
            #getActiveUser,
            [],
          ),
        )),
      ) as _i26.Future<_i14.User>);

  @override
  _i26.Stream<_i14.User> watchGetActiveUser() => (super.noSuchMethod(
        Invocation.method(
          #watchGetActiveUser,
          [],
        ),
        returnValue: _i26.Stream<_i14.User>.empty(),
      ) as _i26.Stream<_i14.User>);

  @override
  _i26.Future<void> deleteUsers() => (super.noSuchMethod(
        Invocation.method(
          #deleteUsers,
          [],
        ),
        returnValue: _i26.Future<void>.value(),
        returnValueForMissingStub: _i26.Future<void>.value(),
      ) as _i26.Future<void>);
}
